let S = null;
let me = localStorage.getItem('bwmilsim-name') || 'Gast';
let currentView = 'dashboard';
let es = null;
const $ = (s) => document.querySelector(s);
const esc = (v='') => String(v).replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const initials = (v='') => v.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase() || 'G';
const fmtTime = (iso) => new Date(iso).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'});

async function api(url, options={}) {
  const r = await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  const data = await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(data.error || `HTTP ${r.status}`);
  return data;
}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function setView(view){currentView=view;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(`#view-${view}`).classList.add('active-view');render();}
function layoutHead(eyebrow,title,sub,buttons=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><div class="page-title">${title}</div><p class="page-sub">${sub}</p></div><div class="actions">${buttons}</div></div>`}
function card(title,body,cls=''){return `<div class="card ${cls}"><div class="section-card"><h3>${title}</h3>${body}</div></div>`}
function tag(text,type=''){return `<span class="tag ${type}">${esc(text)}</span>`}

function dashboard(){
  const ready=S.personnel.filter(p=>p.ready&&p.active).length, active=S.personnel.filter(p=>p.active).length;
  const open=S.tasks.filter(t=>t.status!=='ERLEDIGT').length;
  return layoutHead('OPERATIONSZENTRALE', 'Führung & Lage', `Gemeinsame Einsatzübersicht für ${esc(S.meta.operation)} · ${esc(S.meta.phase)}`, `<button class="btn primary" onclick="setView('map')">Lagekarte öffnen</button><button class="btn" onclick="quickReport()">+ Lagemeldung</button>`)+
  `<div class="grid g4"><div class="card metric good"><div class="metric-label">Einsatzbereitschaft</div><div class="metric-value">${active?Math.round(ready/active*100):0}%</div><div class="metric-foot">${ready} / ${active} Personal bereit</div></div><div class="card metric"><div class="metric-label">Aufträge offen</div><div class="metric-value">${open}</div><div class="metric-foot">${S.tasks.filter(t=>t.priority==='HOCH'&&t.status!=='ERLEDIGT').length} mit hoher Priorität</div></div><div class="card metric warn"><div class="metric-label">Operationsphase</div><div class="metric-value" style="font-size:21px">${esc(S.meta.phase)}</div><div class="metric-foot">Status: ${esc(S.meta.status)}</div></div><div class="card metric"><div class="metric-label">Verbunden</div><div class="metric-value">LIVE</div><div class="metric-foot">Gemeinsamer Server-Zustand</div></div></div>
  <div class="grid g2" style="margin-top:14px"><div class="card"><div class="section-card"><div class="row"><div><h3>Auftragslage</h3><p class="desc">Aktuelle Aufgaben und Bearbeitungsstand</p></div><button class="btn" onclick="setView('tasks')">Alle Aufträge</button></div><div class="mini-list">${S.tasks.slice(0,5).map(taskRow).join('')||'<div class="empty">Keine Aufträge vorhanden.</div>'}</div></div></div>
  <div class="card"><div class="section-card"><div class="row"><div><h3>Letzte Meldungen</h3><p class="desc">Chronologische Lagemeldungen</p></div><button class="btn" onclick="setView('reports')">Meldungen</button></div><div class="feed">${S.reports.slice(0,6).map(reportRow).join('')||'<div class="empty">Noch keine Meldungen.</div>'}</div></div></div></div>
  <div class="grid g3" style="margin-top:14px"><div class="card"><div class="section-card"><h3>Einheiten</h3><p class="desc">Status der aktuell relevanten Elemente</p>${S.units.map(u=>`<div class="list-row"><div class="row"><b>${esc(u.name)}</b>${tag(u.status,u.status==='Bereit'?'accent':'')}</div><div class="meta" style="margin:5px 0">${esc(u.type)} · ${esc(u.readiness)}% Bereitschaft</div><div class="bar"><i style="width:${Math.max(0,Math.min(100,u.readiness))}%"></i></div></div>`).join('')}</div></div>
  ${card('Operationsparameter', `<div class="stack"><div class="row"><span class="meta">Operation</span><b>${esc(S.meta.operation)}</b></div><div class="row"><span class="meta">Phase</span>${tag(S.meta.phase,'accent')}</div><div class="row"><span class="meta">Status</span>${tag(S.meta.status)}</div><div class="row"><span class="meta">Marker</span><b>${S.markers.length}</b></div></div>`)}` + '</div>';
}
function taskRow(t){const c=t.status==='ERLEDIGT'?'accent':t.priority==='HOCH'?'danger':t.status==='IN ARBEIT'?'warn':'';return `<div class="list-row"><div class="row"><b>${esc(t.title)}</b>${tag(t.status,c)}</div><div class="meta">${esc(t.unit)} · ${esc(t.priority)} · Fällig ${esc(t.due)}</div></div>`}
function reportRow(r){return `<div class="feed-item"><b>${esc(r.type)} · ${esc(r.author)}</b><p>${esc(r.text)}</p><small>${fmtTime(r.time)}</small></div>`}

function operation(){return layoutHead('OPERATION',S.meta.operation,'Missionssteuerung und gemeinsamer Operationsstatus',`<button class="btn primary" onclick="advancePhase()">Phase fortschalten</button>`)+`<div class="grid g2"><div class="card"><div class="section-card"><h3>Operationsstatus</h3><p class="desc">Änderungen werden unmittelbar an alle verbundenen Clients verteilt.</p><div class="form"><div class="form-grid"><div class="field"><label>Operationsname</label><input id="op-name" value="${esc(S.meta.operation)}"></div><div class="field"><label>Status</label><select id="op-status"><option>Vorbereitung</option><option>Aktiv</option><option>Pause</option><option>Abgeschlossen</option></select></div></div><div class="field"><label>Phase</label><select id="op-phase"><option>PLANUNG</option><option>BRIEFING</option><option>BEREITSTELLUNG</option><option>DURCHFÜHRUNG</option><option>EXFILTRATION</option><option>AAR</option><option>ABGESCHLOSSEN</option></select></div><button class="btn primary" onclick="saveOperation()">Operationsstatus speichern</button></div></div></div><div class="card"><div class="section-card"><h3>Missionsablauf</h3><p class="desc">Strukturierter Ablauf von der Vorbereitung bis zur AAR.</p><div class="stack">${['PLANUNG','BRIEFING','BEREITSTELLUNG','DURCHFÜHRUNG','EXFILTRATION','AAR','ABGESCHLOSSEN'].map((p,i)=>`<div class="row"><div style="display:flex;gap:9px;align-items:center"><span style="width:22px;height:22px;border-radius:50%;display:grid;place-items:center;border:1px solid ${S.meta.phase===p?'#a7bd55':'#303a32'};color:${S.meta.phase===p?'#b6cf5b':'#657269'}">${i+1}</span><b style="color:${S.meta.phase===p?'#edf3e8':'#859189'}">${p}</b></div>${S.meta.phase===p?tag('AKTIV','accent'):''}</div>`).join('')}</div></div></div></div>`}
async function saveOperation(){await api('/api/operation',{method:'PATCH',body:JSON.stringify({actor:me,changes:{operation:$('#op-name').value,phase:$('#op-phase').value,status:$('#op-status').value}})});toast('Operationsstatus synchronisiert')}
async function advancePhase(){const p=['PLANUNG','BRIEFING','BEREITSTELLUNG','DURCHFÜHRUNG','EXFILTRATION','AAR','ABGESCHLOSSEN'];const i=Math.min(p.length-1,p.indexOf(S.meta.phase)+1);await api('/api/operation',{method:'PATCH',body:JSON.stringify({actor:me,changes:{phase:p[i]}})});toast(`Phase: ${p[i]}`)}

function mapView(){return layoutHead('TAKTISCHE LAGE', 'Lagekarte', 'Gemeinsame Marker- und Auftragslage. Marker werden serverseitig gespeichert und synchronisiert.',`<button class="btn primary" onclick="addMarkerPrompt()">+ Marker setzen</button>`)+`<div class="map-card" id="tacticalMap"><div class="map-grid"></div>${S.markers.map(m=>`<div class="marker ${esc(m.type)}" style="left:${m.x}%;top:${m.y}%" title="${esc(m.label)}" onclick="editMarker('${m.id}')"><div class="marker-pin"></div><div class="marker-label">${esc(m.label)}</div></div>`).join('')}<div class="map-help">${tag('OBJ', 'accent')}${tag('RP','info')}${tag('MED','danger')}<span class="tag">Klick Marker zum Ändern</span></div></div>`}
async function addMarkerPrompt(){const label=prompt('Bezeichnung des Markers?','NEUER MARKER');if(!label)return;const type=prompt('Typ: objective / rally / medical','objective')||'objective';await api('/api/markers',{method:'POST',body:JSON.stringify({actor:me,label,type,x:35+Math.random()*30,y:30+Math.random()*35})});toast('Marker gesetzt')}
async function editMarker(id){const m=S.markers.find(x=>x.id===id);const label=prompt('Neue Bezeichnung',m.label);if(label===null)return;await api(`/api/markers/${id}`,{method:'PATCH',body:JSON.stringify({actor:me,changes:{label}})});toast('Marker aktualisiert')}

function tasks(){return layoutHead('AUFTRÄGE', 'Auftragsverwaltung', 'Von der Führungsentscheidung bis zur Erledigung nachvollziehbar.',`<button class="btn primary" onclick="openTaskModal()">+ Neuer Auftrag</button>`)+`<div class="card table-wrap"><table class="table"><thead><tr><th>Auftrag</th><th>Einheit</th><th>Priorität</th><th>Status</th><th>Fällig</th><th></th></tr></thead><tbody>${S.tasks.map(t=>`<tr><td><b>${esc(t.title)}</b><div class="meta">${esc(t.id)}</div></td><td>${esc(t.unit)}</td><td>${tag(t.priority,t.priority==='HOCH'?'danger':t.priority==='NIEDRIG'?'':'warn')}</td><td>${tag(t.status,t.status==='ERLEDIGT'?'accent':t.status==='IN ARBEIT'?'warn':'')}</td><td>${esc(t.due)}</td><td><button class="btn" onclick="cycleTask('${t.id}')">Status ändern</button></td></tr>`).join('')}</tbody></table></div>`}
async function cycleTask(id){const t=S.tasks.find(x=>x.id===id);const a=['OFFEN','IN ARBEIT','ERLEDIGT'];await api(`/api/tasks/${id}`,{method:'PATCH',body:JSON.stringify({actor:me,changes:{status:a[(a.indexOf(t.status)+1)%a.length]}})});toast('Auftragsstatus synchronisiert')}
function openTaskModal(){showModal('Neuer Auftrag',`<div class="form"><div class="field"><label>Bezeichnung</label><input id="m-task-title" placeholder="z. B. OBJ BRAVO sichern"></div><div class="form-grid"><div class="field"><label>Einheit</label><select id="m-task-unit">${S.units.map(u=>`<option>${esc(u.name)}</option>`).join('')}</select></div><div class="field"><label>Priorität</label><select id="m-task-priority"><option>HOCH</option><option>MITTEL</option><option>NIEDRIG</option></select></div></div><div class="field"><label>Fällig um</label><input id="m-task-due" placeholder="22:00"></div><button class="btn primary" onclick="createTask()">Auftrag erstellen</button></div>`)}
async function createTask(){const title=$('#m-task-title').value.trim();if(!title)return;await api('/api/tasks',{method:'POST',body:JSON.stringify({actor:me,title,unit:$('#m-task-unit').value,priority:$('#m-task-priority').value,due:$('#m-task-due').value||'--:--'})});closeModal();toast('Auftrag erstellt')}

function reports(){return layoutHead('GEFECHTSSTAND', 'Meldungen', 'Lagemeldungen, Funkmeldungen und Befehle in einer gemeinsamen Chronologie.',`<button class="btn primary" onclick="quickReport()">+ Meldung</button>`)+`<div class="grid g2"><div class="card"><div class="section-card"><h3>Neue Meldung</h3><p class="desc">Die Meldung wird unmittelbar in der gemeinsamen Lagechronik sichtbar.</p><div class="form"><div class="form-grid"><div class="field"><label>Meldungsart</label><select id="report-type"><option>LAGEMELDUNG</option><option>BEFEHL</option><option>FUNKMELDUNG</option><option>SANITÄT</option><option>LOGISTIK</option></select></div><div class="field"><label>Absender</label><input id="report-author" value="${esc(me)}"></div></div><div class="field"><label>Text</label><textarea id="report-text" placeholder="Melde…"></textarea></div><button class="btn primary" onclick="createReport()">Meldung absenden</button></div></div></div><div class="card"><div class="section-card"><h3>Chronik</h3><p class="desc">Neueste Meldungen stehen oben.</p><div class="feed">${S.reports.map(reportRow).join('')}</div></div></div></div>`}
function quickReport(){setView('reports');setTimeout(()=>$('#report-text')?.focus(),50)}
async function createReport(){const text=$('#report-text').value.trim();if(!text)return;await api('/api/reports',{method:'POST',body:JSON.stringify({author:$('#report-author').value||me,type:$('#report-type').value,text})});$('#report-text').value='';toast('Meldung veröffentlicht')}

function personnel(){return layoutHead('PERSONAL', 'Personalstamm', 'Dienstgrade, Callsigns, Funktionen und Bereitschaft zentral verwalten.',`<button class="btn primary" onclick="openPersonnelModal()">+ Personal anlegen</button>`)+`<div class="card table-wrap"><table class="table"><thead><tr><th>Person</th><th>Dienstgrad</th><th>Callsign</th><th>Funktion</th><th>Einheit</th><th>Bereitschaft</th></tr></thead><tbody>${S.personnel.map(p=>`<tr><td><div class="person"><div class="avatar">${initials(p.name)}</div><div><b>${esc(p.name)}</b><span>${p.active?'AKTIV':'INAKTIV'}</span></div></div></td><td>${tag(p.rank,'accent')}</td><td class="code">${esc(p.callsign)}</td><td>${esc(p.role)}</td><td>${esc(p.unit)}</td><td><button class="btn" onclick="toggleReady('${p.id}')">${p.ready?'BEREIT':'NICHT BEREIT'}</button></td></tr>`).join('')}</tbody></table></div>`}
async function toggleReady(id){const p=S.personnel.find(x=>x.id===id);await api(`/api/personnel/${id}`,{method:'PATCH',body:JSON.stringify({actor:me,changes:{ready:!p.ready}})});toast(`${p.name}: ${!p.ready?'bereit':'nicht bereit'}`)}
function openPersonnelModal(){showModal('Personal anlegen',`<div class="form"><div class="form-grid"><div class="field"><label>Name</label><input id="p-name"></div><div class="field"><label>Callsign</label><input id="p-call" placeholder="ALPHA 1-4"></div></div><div class="form-grid"><div class="field"><label>Dienstgrad</label><select id="p-rank"><option>Gefreiter</option><option>Obergefreiter</option><option>Hauptgefreiter</option><option>Stabsgefreiter</option><option>Oberstabsgefreiter</option><option>Unteroffizier</option><option>Feldwebel</option><option>Hauptfeldwebel</option><option>Stabsfeldwebel</option><option>Leutnant</option><option>Oberleutnant</option><option>Hauptmann</option><option>Major</option><option>Oberstleutnant</option><option>Oberst</option></select></div><div class="field"><label>Funktion</label><input id="p-role" placeholder="Schütze"></div></div><div class="field"><label>Einheit</label><select id="p-unit">${S.units.map(u=>`<option>${esc(u.name)}</option>`).join('')}</select></div><button class="btn primary" onclick="createPersonnel()">Person anlegen</button></div>`)}
async function createPersonnel(){const name=$('#p-name').value.trim();if(!name)return;await api('/api/personnel',{method:'POST',body:JSON.stringify({actor:me,name,callsign:$('#p-call').value,rank:$('#p-rank').value,role:$('#p-role').value,unit:$('#p-unit').value})});closeModal();toast('Personal angelegt')}

function organization(){return layoutHead('ORGANISATION', 'Einheiten & Struktur', 'Hierarchische Darstellung der gemeinsamen Milsim-Organisation.',`<button class="btn" onclick="setView('personnel')">Personalbestand</button>`)+`<div class="grid g2"><div class="card"><div class="section-card"><h3>Organigramm</h3><p class="desc">Führungsverhältnisse und unterstellte Elemente.</p><div class="tree"><div class="tree-root">Kampfkompanie</div>${S.units.filter(u=>u.parent==='Kampfkompanie').map(u=>unitTree(u,0)).join('')}</div></div></div><div class="card"><div class="section-card"><h3>Bereitschaft nach Einheit</h3><p class="desc">Operative Verfügbarkeit des Personals.</p>${S.units.map(u=>{const ps=S.personnel.filter(p=>p.unit===u.name&&p.active),r=ps.length?Math.round(ps.filter(p=>p.ready).length/ps.length*100):0;return `<div class="list-row"><div class="row"><b>${esc(u.name)}</b><span>${r}%</span></div><div class="meta" style="margin:4px 0 7px">${ps.filter(p=>p.ready).length}/${ps.length} bereit</div><div class="bar"><i style="width:${r}%"></i></div></div>`}).join('')}</div></div></div>`}
function unitTree(u,depth){const commander=S.personnel.find(p=>p.id===u.commander);return `<div class="tree-node"><div class="row"><b>${esc(u.name)}</b>${tag(u.status,u.status==='Bereit'?'accent':'')}</div><div class="meta">${esc(u.type)} · ${commander?esc(commander.rank+' '+commander.name):'Führung nicht zugewiesen'}</div>${S.units.filter(x=>x.parent===u.name).map(x=>unitTree(x,depth+1)).join('')}</div>`}

function ranksView(){const ranks=['General','Generalleutnant','Generalmajor','Brigadegeneral','Oberst','Oberstleutnant','Major','Hauptmann','Oberleutnant','Leutnant','Stabsfeldwebel','Oberstabsfeldwebel','Hauptfeldwebel','Oberfeldwebel','Feldwebel','Stabsunteroffizier','Unteroffizier','Oberstabsgefreiter','Stabsgefreiter','Hauptgefreiter','Obergefreiter','Gefreiter','Schütze / Matrose / Flieger'];return layoutHead('DIENSTGRADE','Bundeswehr-nahe Dienstgradordnung','Konfigurierbare Dienstgrade für Personal und Führungsfunktionen.')+`<div class="card"><div class="section-card">${ranks.map((r,i)=>`<div class="rank-strip"><span class="rank-index">${String(i+1).padStart(2,'0')}</span><span class="rank-name">${r}</span><span class="rank-line"></span><span class="rank-badge">${i<10?'OFFIZIER':i<18?'FELDWEBEL':'MANNSCHAFT'}</span></div>`).join('')}</div></div>`}

function aar(){return layoutHead('AFTER ACTION REVIEW','Nachbesprechung / AAR','Erfahrungen, Ereignisse und konkrete Folgemaßnahmen strukturiert festhalten.',`<button class="btn primary" onclick="saveAAR()">AAR speichern</button>`)+`<div class="grid g2"><div class="card"><div class="section-card"><h3>Einsatzbewertung</h3><p class="desc">Freie Dokumentation für die Abschlussbesprechung.</p><div class="form"><div class="field"><label>Zusammenfassung</label><textarea id="aar-summary">${esc(S.aar.summary)}</textarea></div><div class="field"><label>Was hat funktioniert?</label><textarea id="aar-successes">${esc(S.aar.successes)}</textarea></div><div class="field"><label>Was hat nicht funktioniert?</label><textarea id="aar-failures">${esc(S.aar.failures)}</textarea></div><div class="field"><label>Lessons Learned</label><textarea id="aar-lessons">${esc(S.aar.lessons)}</textarea></div></div></div></div><div class="card"><div class="section-card"><h3>Automatische Einsatzchronik</h3><p class="desc">Die AAR-Basis aus dem gemeinsamen Audit-Log.</p><div class="feed">${S.audit.slice(0,14).map(a=>`<div class="feed-item"><b>${esc(a.action)}</b><p>${esc(a.detail)}</p><small>${fmtTime(a.time)} · ${esc(a.actor)}</small></div>`).join('')||'<div class="empty">Noch keine Ereignisse.</div>'}</div></div></div></div>`}
async function saveAAR(){await api('/api/aar',{method:'PATCH',body:JSON.stringify({actor:me,changes:{summary:$('#aar-summary').value,successes:$('#aar-successes').value,failures:$('#aar-failures').value,lessons:$('#aar-lessons').value}})});toast('AAR gespeichert und synchronisiert')}
function history(){return layoutHead('AUDIT','Verlauf','Nachvollziehbarer Änderungsverlauf der gemeinsamen Operationsdaten.')+`<div class="card"><div class="section-card"><div class="feed">${S.audit.map(a=>`<div class="feed-item"><b>${esc(a.action)}</b><p>${esc(a.detail)}</p><small>${fmtTime(a.time)} · ${esc(a.actor)}</small></div>`).join('')||'<div class="empty">Noch keine Änderungsereignisse.</div>'}</div></div></div>`}
function settings(){return layoutHead('SYSTEM','Einstellungen','Lokale Server- und Client-Hinweise für den gemeinsamen Betrieb.')+`<div class="grid g2"><div class="card"><div class="section-card"><h3>Lokaler Betrieb</h3><p class="desc">Der Server speichert den gemeinsamen Zustand lokal in <span class="code">data/state.json</span>.</p><div class="stack"><div class="row"><span class="meta">Server</span><b>Node.js</b></div><div class="row"><span class="meta">Echtzeit</span><b>Server-Sent Events</b></div><div class="row"><span class="meta">Port</span><b class="code">3000</b></div><div class="row"><span class="meta">Cloud-Abhängigkeit</span><b>Keine</b></div></div></div></div><div class="card"><div class="section-card"><h3>Dein Profil</h3><p class="desc">Der Anzeigename wird lokal auf diesem Gerät gespeichert.</p><div class="form"><div class="field"><label>Anzeigename</label><input id="settings-name" value="${esc(me)}"></div><button class="btn primary" onclick="saveProfile()">Profil speichern</button></div></div></div></div>`}
function saveProfile(){me=$('#settings-name').value.trim()||'Gast';localStorage.setItem('bwmilsim-name',me);updateProfile();toast('Profil lokal gespeichert')}
function updateProfile(){$('#meName').textContent=me;$('#meInitial').textContent=initials(me)}

function showModal(title,body){$('#modal').innerHTML=`<div class="modal"><div class="modal-head"><b>${esc(title)}</b><button class="close" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div></div>`;$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML=''}
function profileModal(){showModal('Lokales Profil',`<div class="form"><div class="field"><label>Anzeigename</label><input id="profile-name" value="${esc(me)}"></div><button class="btn primary" onclick="me=$('#profile-name').value.trim()||'Gast';localStorage.setItem('bwmilsim-name',me);updateProfile();closeModal();toast('Profil aktualisiert')">Speichern</button></div>`)}
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});

function render(){if(!S)return;document.querySelectorAll('.view').forEach(v=>v.innerHTML='');
  const renderers={dashboard,operation,map:mapView,tasks,reports,personnel,organization,ranks:ranksView,aar,history,settings};
  $(`#view-${currentView}`).innerHTML=renderers[currentView]();
  if(currentView==='operation'){$('#op-phase').value=S.meta.phase;$('#op-status').value=S.meta.status}
  updateProfile();
}
function connectEvents(){if(es)es.close();es=new EventSource('/api/events');es.onopen=()=>{$('#connectionText').textContent='VERBUNDEN';document.querySelector('.top-status .live-dot').style.background='#6fbd57'};es.onerror=()=>{$('#connectionText').textContent='RECONNECTING…';document.querySelector('.top-status .live-dot').style.background='#e7b45e'};es.addEventListener('connected',e=>{const d=JSON.parse(e.data);S=d.state;render()});es.onmessage=e=>{const d=JSON.parse(e.data);if(d.state){S=d.state;render();toast(`Synchronisiert: ${d.event?.type||'Änderung'}`)}}}
async function boot(){S=await api('/api/state');render();connectEvents();setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('de-DE'),1000);}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>setView(n.dataset.view)));
$('#profileBtn').addEventListener('click',profileModal);
boot().catch(e=>{console.error(e);$('#connectionText').textContent='SERVER FEHLER';$('#connectionText').style.color='#df6d67'});
window.setView=setView;window.quickReport=quickReport;window.openTaskModal=openTaskModal;window.createTask=createTask;window.cycleTask=cycleTask;window.createReport=createReport;window.addMarkerPrompt=addMarkerPrompt;window.editMarker=editMarker;window.toggleReady=toggleReady;window.openPersonnelModal=openPersonnelModal;window.createPersonnel=createPersonnel;window.saveOperation=saveOperation;window.advancePhase=advancePhase;window.saveAAR=saveAAR;window.saveProfile=saveProfile;window.closeModal=closeModal;
