(() => {
  const style = document.createElement('style');
  style.textContent = `.map3d-shell{position:relative;height:min(76vh,760px);min-height:560px;background:#081008;border:1px solid #29362b;border-radius:12px;overflow:hidden;box-shadow:0 20px 45px rgba(0,0,0,.35)}.map3d-canvas{position:absolute;inset:0}.map3d-canvas canvas{display:block;width:100%;height:100%}.map3d-hud{position:absolute;inset:0;pointer-events:none}.map3d-toolbar{position:absolute;top:12px;left:12px;right:12px;display:flex;justify-content:space-between;gap:10px;align-items:flex-start;pointer-events:auto}.map3d-cluster{display:flex;gap:7px;flex-wrap:wrap}.map3d-btn{border:1px solid #354338;background:rgba(10,15,11,.88);color:#e0e8df;border-radius:7px;padding:8px 10px;font:11px Inter,Segoe UI,system-ui,sans-serif;cursor:pointer;backdrop-filter:blur(8px)}.map3d-btn:hover,.map3d-btn.active{border-color:#718c4b;color:#c5dd78;background:#182018}.map3d-readout{max-width:430px;padding:10px 12px;border:1px solid #354338;background:rgba(10,15,11,.88);border-radius:8px;color:#b7c2b8;font:10px/1.45 Inter,Segoe UI,system-ui,sans-serif;backdrop-filter:blur(8px)}.map3d-readout b{color:#e6eee5;letter-spacing:.06em}.map3d-bottom{position:absolute;left:12px;right:12px;bottom:12px;display:flex;justify-content:space-between;align-items:flex-end;gap:12px;pointer-events:none}.map3d-legend,.map3d-compass{border:1px solid #354338;background:rgba(10,15,11,.88);border-radius:8px;padding:9px 10px;backdrop-filter:blur(8px)}.map3d-legend{display:flex;gap:9px;flex-wrap:wrap;color:#adb8ae;font:9px/1 Inter,Segoe UI,system-ui,sans-serif}.map3d-key{display:flex;align-items:center;gap:5px}.map3d-dot{width:8px;height:8px;border-radius:50%;display:inline-block}.map3d-dot.obj{background:#b7d560}.map3d-dot.rp{background:#7eb4d9}.map3d-dot.med{background:#df8c86}.map3d-dot.unit{background:#fff0a0}.map3d-compass{width:64px;height:64px;display:grid;place-items:center;position:relative;color:#dfe9df;font:bold 10px/1 Inter,Segoe UI,system-ui,sans-serif}.map3d-compass:before{content:'';position:absolute;width:30px;height:30px;border:1px solid #4a5a48;transform:rotate(45deg)}.map3d-compass:after{content:'▲';position:absolute;top:7px;color:#c4db72}.map3d-tip{position:absolute;left:50%;bottom:85px;transform:translateX(-50%);padding:7px 10px;border:1px solid #354338;background:rgba(10,15,11,.82);border-radius:7px;color:#89958c;font:9px/1.4 Inter,Segoe UI,system-ui,sans-serif;white-space:nowrap;pointer-events:none}@media(max-width:760px){.map3d-shell{min-height:500px}.map3d-readout{display:none}.map3d-tip{display:none}}`;
  document.head.appendChild(style);

  let scene, camera, renderer, terrain, grid, labels, markerGroup, resizeObserver, raf;
  let yaw=.72, pitch=.72, distance=185, tx=0, ty=3, tz=0;
  let dragging=false, pan=false, lx=0, ly=0, downX=0, downY=0, moved=false;
  const W=220, D=180, NX=181, NZ=151;
  const ray=new THREE.Raycaster(), pointer=new THREE.Vector2();
  const places=[['KAVALA',-61,-34],['PYRGOS',32,-4],['ATHIRA',-8,-13],['SOFIA',-28,34],['NEOCHORI',15,37],['ZAROS',-54,28],['OREOKASTRO',49,-41],['AGIOS DIONYSIOS',74,17],['ALTIS INTL. AIRPORT',3,-63]];
  function gauss(x,z,cx,cz,sx,sz,a){const dx=(x-cx)/sx,dz=(z-cz)/sz;return a*Math.exp(-(dx*dx+dz*dz))}
  function ell(x,z,cx,cz,rx,rz){const q=((x-cx)*(x-cx))/(rx*rx)+((z-cz)*(z-cz))/(rz*rz);return Math.max(0,1-q)}
  function mask(x,z){return Math.max(0,Math.max(ell(x,z,-.18,-.02,.83,.63),ell(x,z,.48,-.08,.48,.69),ell(x,z,-.72,.06,.31,.40),ell(x,z,.05,.64,.43,.29),ell(x,z,.80,.15,.22,.31))-ell(x,z,.16,.03,.27,.31)*.9-ell(x,z,.52,.20,.15,.25)*.42)}
  function height(x,z){const nx=x/(W*.5),nz=z/(D*.5),m=mask(nx,nz);if(m<=.01)return -2.2;const mountains=gauss(nx,nz,-.13,-.08,.22,.26,15.5)+gauss(nx,nz,.25,.02,.18,.24,10)+gauss(nx,nz,-.53,.02,.20,.24,7)+gauss(nx,nz,.02,.57,.20,.16,6.3);const ridges=(Math.sin(nx*13.4+Math.cos(nz*3.3))*.5+.5)*1.7+(Math.sin(nz*19+nx*6)*.5+.5)*1.15;return Math.max(.25,.7+Math.pow(m,.44)*(mountains+ridges+2.8+1.7*Math.sin(nx*4.4)*Math.cos(nz*3.6)))}
  function terrainColor(v){const c=new THREE.Color();if(v<1.5){const t=Math.max(0,Math.min(1,(v-.2)/1.3));c.setRGB(.30+t*.06,.43+t*.10,.22+t*.04)}else if(v<6){const t=(v-1.5)/4.5;c.setRGB(.36+t*.16,.48+t*.10,.25+t*.05)}else{const t=Math.min(1,(v-6)/13);c.setRGB(.50+t*.20,.49+t*.15,.30+t*.13)}return c}
  function sprite(text,color='#dbe6d9',border='rgba(83,102,74,.9)'){const c=document.createElement('canvas');c.width=512;c.height=96;const g=c.getContext('2d');g.fillStyle='rgba(7,12,8,.84)';g.strokeStyle=border;g.beginPath();g.roundRect(2,2,508,92,10);g.fill();g.stroke();g.fillStyle=color;g.font='600 26px Inter,Segoe UI,Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(text,256,49);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(15,2.8,1);return s}
  function build(){const g=new THREE.PlaneGeometry(W,D,NX-1,NZ-1);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors=new Float32Array(p.count*3);for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),v=height(x,z);p.setY(i,v);const c=v<0?new THREE.Color(.04,.10,.07):terrainColor(v);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b}g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.computeVertexNormals();terrain=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.98}));scene.add(terrain);const water=new THREE.Mesh(new THREE.PlaneGeometry(W+35,D+35),new THREE.MeshStandardMaterial({color:0x102b2f,roughness:.45,transparent:true,opacity:.93}));water.rotation.x=-Math.PI/2;water.position.y=-2.15;scene.add(water);grid=new THREE.GridHelper(220,22,0x384538,0x1b241c);grid.position.y=-2.05;scene.add(grid);labels=new THREE.Group();for(const [name,x,z] of places){const s=sprite(name,'#c6d2c5','rgba(60,79,60,.75)');s.position.set(x,height(x,z)+3.5,z);labels.add(s)}scene.add(labels);buildMarkers()}
  function buildMarkers(){if(markerGroup)scene.remove(markerGroup);markerGroup=new THREE.Group();const ms=window.S&&Array.isArray(S.markers)?S.markers:[];for(const m of ms){const col=m.type==='rally'?0x7eb4d9:m.type==='medical'?0xdf8c86:0xb7d560;const x=((Number(m.x)||50)/100-.5)*W,z=((Number(m.y)||50)/100-.5)*D,y=height(x,z)+2;const q=new THREE.Group();const ring=new THREE.Mesh(new THREE.RingGeometry(.8,1.05,24),new THREE.MeshBasicMaterial({color:col,transparent:true,opacity:.9,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=y;ring.userData.markerId=m.id;const pin=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,3.6,10),new THREE.MeshBasicMaterial({color:col}));pin.position.y=y+1.8;pin.userData.markerId=m.id;const lab=sprite(m.label||'MARKER','#eef4ea',col===0xb7d560?'rgba(104,129,55,.95)':col===0x7eb4d9?'rgba(58,94,114,.95)':'rgba(116,64,61,.95)');lab.position.set(x+1.2,y+4,z);lab.userData.markerId=m.id;q.add(ring,pin,lab);markerGroup.add(q)}scene.add(markerGroup)}
  function updateCamera(){pitch=Math.max(.27,Math.min(1.52,pitch));camera.position.set(tx+distance*Math.cos(pitch)*Math.sin(yaw),ty+distance*Math.sin(pitch),tz+distance*Math.cos(pitch)*Math.cos(yaw));camera.lookAt(tx,ty,tz)}
  function resize(){if(!renderer)return;const el=document.getElementById('altis3dCanvas'),w=el?.clientWidth||900,h=el?.clientHeight||600;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2))}
  function pointer(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1}
  function pick(e){pointer(e);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(markerGroup?.children||[],true).find(x=>x.object.userData.markerId);return hit?.object.userData.markerId||null}
  function bind(){const el=renderer.domElement;el.oncontextmenu=e=>e.preventDefault();el.onpointerdown=e=>{dragging=true;pan=e.shiftKey||e.button===2;moved=false;lx=downX=e.clientX;ly=downY=e.clientY;el.setPointerCapture?.(e.pointerId)};el.onpointermove=e=>{if(!dragging)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;if(Math.abs(e.clientX-downX)+Math.abs(e.clientY-downY)>4)moved=true;if(pan){const s=distance*.0023,r={x:Math.cos(yaw),z:-Math.sin(yaw)},f={x:Math.sin(yaw),z:Math.cos(yaw)};tx-=(dx*r.x+dy*f.x)*s;tz-=(dx*r.z+dy*f.z)*s}else{yaw-=dx*.008;pitch=Math.max(.27,Math.min(1.45,pitch-dy*.006))}updateCamera()};el.onpointerup=e=>{const mm=moved;dragging=false;if(!mm){const id=pick(e);if(id&&typeof window.editMarker==='function')window.editMarker(id)}};el.onwheel=e=>{e.preventDefault();distance=Math.max(45,Math.min(320,distance*(e.deltaY>0?1.09:.91)));updateCamera()};el.ondblclick=e=>{pointer(e);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(terrain,false)[0];if(!hit)return;const px=Math.round(((hit.point.x/W)+.5)*100),py=Math.round(((hit.point.z/D)+.5)*100),label=prompt('Marker-Bezeichnung','NEUER MARKER');if(!label)return;const type=prompt('Typ: objective / rally / medical','objective')||'objective';fetch('/api/markers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:window.me||'Gast',label,type,x:px,y:py})})}}
  function init(){const root=document.getElementById('tacticalMap3D');if(!root||!window.THREE)return;scene=new THREE.Scene();scene.background=new THREE.Color(0x081009);scene.fog=new THREE.FogExp2(0x081009,.0028);camera=new THREE.PerspectiveCamera(48,1,.1,1000);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;document.getElementById('altis3dCanvas').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xbfcbbd,0x152018,2));const sun=new THREE.DirectionalLight(0xf2f0d7,2.25);sun.position.set(-110,165,80);scene.add(sun);build();updateCamera();bind();resize();resizeObserver=new ResizeObserver(resize);resizeObserver.observe(document.getElementById('altis3dCanvas'));const gridBtn=document.getElementById('map3d-grid'),labelBtn=document.getElementById('map3d-labels');document.getElementById('map3d-reset').onclick=()=>{yaw=.72;pitch=.72;distance=185;tx=0;ty=3;tz=0;updateCamera()};document.getElementById('map3d-top').onclick=()=>{yaw=0;pitch=1.52;distance=195;tx=0;ty=0;tz=0;updateCamera()};gridBtn.onclick=()=>{grid.visible=!grid.visible;gridBtn.classList.toggle('active',grid.visible)};labelBtn.onclick=()=>{labels.visible=!labels.visible;labelBtn.classList.toggle('active',labels.visible)};const loop=()=>{renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop()}
  function destroy(){if(raf)cancelAnimationFrame(raf);resizeObserver?.disconnect?.();renderer?.dispose?.();renderer?.domElement?.remove?.();scene=camera=renderer=terrain=grid=labels=markerGroup=null}
  window.mapView=() => {destroy();const html=window.layoutHead('TAKTISCHE LAGE','3D-Lagekarte','Vollständige Inselansicht mit Gelände, Höhenmodell und gemeinsam synchronisierten Lageobjekten.',`<button class="btn primary" onclick="addMarkerPrompt()">+ Marker setzen</button>`)+`<div class="map3d-shell" id="tacticalMap3D"><div class="map3d-canvas" id="altis3dCanvas"></div><div class="map3d-hud"><div class="map3d-toolbar"><div class="map3d-cluster"><button class="map3d-btn active" id="map3d-grid">GRID</button><button class="map3d-btn active" id="map3d-labels">ORTSLABELS</button><button class="map3d-btn" id="map3d-top">TOP-DOWN</button><button class="map3d-btn" id="map3d-reset">AUSGANGSLAGE</button></div><div class="map3d-readout"><b>ALTIS · 3D LAGEKARTE</b><br>Vollinsel-Terrain · Höhenmodell · gemeinsame Lageobjekte<br>Die Terrainbasis ist schematisch und kann später durch ausdrücklich lizenzierte Geländedaten ersetzt werden.</div></div><div class="map3d-bottom"><div class="map3d-legend"><span class="map3d-key"><i class="map3d-dot obj"></i>OBJ</span><span class="map3d-key"><i class="map3d-dot rp"></i>RP</span><span class="map3d-key"><i class="map3d-dot med"></i>MED</span></div><div class="map3d-compass">N</div></div><div class="map3d-tip">Linke Maustaste: drehen · Shift + Maus: verschieben · Mausrad: zoomen · Doppelklick: Marker</div></div></div>`;setTimeout(init,0);return html}
})();
